### ISSUE TITLE
migrate to gihtub actions

### ISSUE THREAD

**Issue by amilajack** [amilajack/node-disk-utility#39]

**Comment by staltz** [comment]
Hey! Thanks for your package, it's serving me as a template to write my own neon module on npm.

I managed to use GitHub actions correctly, so for this issue, you might want to take a look at how I did it at https://github.com/staltz/ssb-neon-keys . If you allow me to have a slightly off-topic conversation here (because it's hard to find other example projects), I'm having difficulties *installing* such modules, see issue #41 .

**Comment by amilajack** [comment]
@staltz sorry for the late response, I'll take a look at https://github.com/amilajack/node-disk-utility/issues/41.
